spring:
    http:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    mail:
        host: ${mail.host}
        username: ${mail.username}
        password: ${mail.password}
        properties:
            mail:
                smtp:
                    auth: true
                    socketFactory:
                        port: 465
                        class: javax.net.ssl.SSLSocketFactory
                        fallback: false
                    starttls:
                        enable: true
                    ssl:
                        enabled: true

jwt:
    secret: ${jwt.secret}
    expiration: 28800000
    
---

user:
    super:
        password: ${user.super.password}